accepted_secrets:
  - "tests/test-secret-gate.sh:generic-api-key:58:f8b2dfc70600cc20"
  - "tests/test-secret-gate.sh:github-pat:745:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:734:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:649:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:614:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:559:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:503:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:460:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:435:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:67:3c039e86de0f2615"
  - "tests/test-secret-gate.sh:github-pat:66:4b09b09836f5874d"
  - "tests/test-secret-gate.sh:github-pat:59:4b09b09836f5874d"
  - "tests/test-vetting.sh:generic-api-key:501:763b2c76468e0df0"
  - "tests/test-vetting.sh:github-pat:501:4b09b09836f5874d"
