#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Samaritan's Purse
# scripts/stamp-version.sh — resolve the CLI's version identity ONCE and embed
# it into a `.version` file that bin/sandbox reads at runtime.
#
# This exists so the runtime never recomputes the version from mutable local
# state (e.g. `git describe`, whose answer depends on which tags a clone happens
# to have fetched). We resolve here — at release time in CI, or at install time
# in a developer's checkout — where git history is available, and freeze the
# result. See docs/how-to/... and bin/sandbox's version reader.
#
# Usage:
#   scripts/stamp-version.sh [VERSION]
#     VERSION given  → used verbatim (the release path; CI passes the tag).
#     VERSION omitted → derived from git: `describe --tags --always --dirty`.
#
# Output path defaults to <repo-root>/.version; override with STAMP_VERSION_OUT
# (the release task points it at the staging dir).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${STAMP_VERSION_OUT:-${ROOT}/.version}"

explicit_version="${1:-}"

git_in_root() {
  command -v git >/dev/null 2>&1 \
    && git -C "${ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1
}

version="dev"
commit=""
commit_date=""
tree_state=""
[[ -n "${explicit_version}" ]] && version="${explicit_version}"

if git_in_root; then
  commit="$(git -C "${ROOT}" rev-parse --short HEAD 2>/dev/null || true)"
  commit_date="$(git -C "${ROOT}" show -s --format=%cs HEAD 2>/dev/null || true)"
  if git -C "${ROOT}" diff --quiet 2>/dev/null \
     && git -C "${ROOT}" diff --cached --quiet 2>/dev/null; then
    tree_state="clean"
  else
    tree_state="dirty"
  fi
  # No explicit version (dev/install path): derive the human label from git.
  if [[ -z "${explicit_version}" ]]; then
    version="$(git -C "${ROOT}" describe --tags --always --dirty 2>/dev/null || echo dev)"
  fi
fi

build_date="$(date -u +%Y-%m-%d)"

{
  echo "# Generated by scripts/stamp-version.sh at build/install time."
  echo "# Read by bin/sandbox; never edit or commit this file."
  echo "VERSION=${version}"
  echo "COMMIT=${commit}"
  echo "COMMIT_DATE=${commit_date}"
  echo "BUILD_DATE=${build_date}"
  echo "TREE_STATE=${tree_state}"
} > "${OUT}"

echo ">> Stamped ${OUT}: ${version} (${commit:-no-git}${tree_state:+, ${tree_state}})"
